# Generated by Django 5.2.8 on 2025-11-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_brand_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity_change',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='unit_price_at_sale',
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('unit_price_at_sale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='api.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='api.transaction')),
            ],
            options={
                'unique_together': {('transaction', 'item')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(related_name='transactions', through='api.TransactionItem', to='api.item'),
        ),
    ]
